
-------------------------------
--- TABLE STRUCTURE FOR products 
-------------------------------

CREATE TABLE products(
    id INTEGER AUTO_INCREMENT NOT NULL UNIQUE,
    nombre VARCHAR(70) NOT NULL,
    descripcion TEXT(500) NOT NULL,
    precio INTEGER NOT NULL,
    numUnidades INTEGER NOT NULL,
    categoria  SET('galletas', 'tortas', 'muffins') NOT NULL,
    imagen VARCHAR(250) NOT NULL, 
    PRIMARY KEY(id)
);

-------------------------------
-- RECORDS OF products 
-------------------------------

INSERT INTO products(nombre, descripcion, precio, numUnidades, categoria, imagen)
VALUES
("Torta negra envinada", "La torta más famosa en Colombia, que es la que llamamos -torta negra-, -torta envinada-, -torta de bodas o de novia-, entre otros nombres. Esta torta es tan popular que es la preferida para servir en ocasiones especiales como bautizos, primeras comuniones, bodas, y días festivos, como la Navidad. Y si creen que ya habían visto una versión similar, están en lo cierto, porque otros países, como Jamaica y Venezuela, también tienen sus propias versiones de esta torta negra.", 50000, 50, "tortas", "https://www.cocina-colombiana.com/base/stock/Post/54-image/54-image_web.jpg"),
("Torta de fresa", "La torta de fresas es una de las tartas clásicas de fruta que se hace de muchas formas y cuya capa superior está hecha normalmente de fresas. Es un postre muy común en toda Europa. Dos de las variedades más comunes son: La base es una capa de pastaflora​ untada de confite sobre la que se presenta una capa de galletas.", 60000, 80, "tortas", "https://comidasvenezolanas.org/wp-content/uploads/2021/02/torta-de-fresa_700x466.jpg"),
("Torta de chocolate", "El pastel de chocolate, tarta de chocolate o torta de chocolate, es un postre conocido internacionalmente, que se popularizó a finales del siglo XIX y se sirve frecuentemente en reuniones, como fiestas de cumpleaños y bodas.", 50000, 40, "tortas", "https://i.ytimg.com/vi/H7uMpjzyaTU/maxresdefault.jpg"),
("Pastel de red velvet", "Es un pastel recubierto de queso crema dulce. Su nombre -Red Velvet- se traduce a -Terciopelo Rojo-, debido a su intenso color rojo, sin embargo, su sabor no es fuerte, en cambio es húmedo, dulce, de textura suave y esponjosa.", 90000, 20, "tortas", "https://www.recetasnestle.com.pe/sites/default/files/srh_recipes/148b74f77f13c5b11e2d6e43cd36916e.jpg"),
("Patel de zanahoria", "El pastel de zanahoria, tarta de zanahoria o torta de zanahoria es un pastel dulce con zanahoria machacada mezclada en la masa. La zanahoria se ablanda en el proceso de cocción, y la tarta suele tener una textura densa y suave. Las zanahorias mejoran el sabor, textura y apariencia del pastel.", 40000, 40, "tortas", "https://i.ytimg.com/vi/m2QlIAyKn14/maxresdefault.jpg"),
("Torta de pan", "La torta de pan, deliciosa solución para las tardes amargas. Postre tradicional e icónico del venezolano, un trozo de esta dulzura trasladará a todos a los felices momentos de la infancia. Los sabores de un rico caramelo y la leche condensada cautivarán a cualquiera. Excelente para compartir en familia y acompañar con una buena taza de café.", 4000, 30, "tortas", "https://img-global.cpcdn.com/recipes/3ed840f4bdbc63d6/1200x630cq70/photo.jpg"),
("Galletas de mantequilla", "Las galletas de mantequilla son la madre de todas las galletas, a pesar de que también se pueden elaborar con otras grasas o con ausencia total de ellas. Hay galletas de aceite exquisitas, otros las prefieren con manteca o con mantequilla de cacahuete, y pueden quedar muy ricas solo con huevo... pero no hay nada como el delicioso sabor y la textura de unas buenas galletas de mantequilla.", 1000, 500, "galletas", "https://unareceta.com/wp-content/uploads/2017/02/galletas-de-mantequilla.jpg"),
("Galletas de chocolate", "Era inevitable encontrar las galletas de chocolate. El cacao es un sabor clásico de multitud de postres y también enriquece a muchas masas de galletas, de nuevo bajo innumerables formas distintas, muy ricas y perfectas para compartir con niños de la casa.", 1500, 1000, "galletas", "https://www.tictacyummy.com/wp-content/uploads/2020/02/PortadaWeb-800x530.jpg"),
("Galletas de avena", "¿Cuándo empezaron a ponerse de moda las galletas de avena? Recuerdo a mi padre sufriendo siempre para encontrar un bote de copos de avena para sus meriendas y ahora es un ingrediente básico de cualquier supermercado. Sea como sea, son otro clásico de la repostería europea y americana, de nuevo bajo muchas formas diferentes. A mí me gustan mucho las clásicas galletas de avena con pasas, que a pesar de ser nutritivas no hay que olvidar que siguen siendo un dulce para tomar ocasionalmente.", 2500, 250, "galletas", "https://imag.bonviveur.com/galletas-de-avena-faciles-y-rapidas.jpg"),
("Galletas de jengibre", "El jengibre solo es una especia que puede aromatizar cientos de galletas y dulces diferentes, si bien se suele asociar con la Navidad. Es imprescindible en los típicos hombres navideños o gingerbread men, cuya masa es la famosa de pan de jengibre, que en realidad lleva muchos más aromas. En cualquier caso, creo que unas verdaderas galletas de jengibre necesitan dar el mayor protagonismo a esta especia tan particular y rica, combinada a ser posible con melaza o miel.", 5000, 1000, "galletas", "https://www.codigococina.com/wp-content/uploads/2016/12/galletas_jengibre_canela.jpg"),
("Galletas de nata", "Unas galletas con un sabor intenso a lácteo pero con un toque suave y delicado. Quizás de nuestras favoritas, rivalizando con las galletas de chocolate crujiente, las galletas de avena o las deliciosas galletas de avellana. El resultado son unas galletas suaves, untuosas y dulces, que, a pesar de no ser exactamente las mismas, se merecen una nota bien alta, estoy seguro de que les gustarán.", 2500, 300, "galletas", "https://vod-hogarmania.atresmedia.com/hogarmania/images/images01/2018/01/10/5c0009185a2c11000177514a/1239x697.jpg"),
("Lenguas de gato rellenas de nata y frambuesa", "Las lenguas de gato son unas galletas de mantequilla con forma alargada. Precisamente se les llama lenguas de gato por su forma. En esta ocasión, les traemos este dulce típico, pero con un toque original. Lenguas de gato con nata y frambuesa. El resultado, ¡espectacular!", 3000, 600, "galletas", "https://www.hogarmania.com/archivos/201507/5579-2-lenguas-de-gato-rellenas-de-nata-y-frambuesa-964-xl-XxXx80.jpg"),
("Galletas integrales", "Muchas veces nos preguntan por galletas para desayunos saludables. Estas galletas integrales con mermelada de kiwi casera de nuestra pastelería son perfectas para un desayuno sano y nutritivo.", 3000, 200, "galletas", "https://www.hogarmania.com/archivos/201108/0062-galletas-integrales-con-mermelada-de-kiwi-668x400x80xX.jpg"),
("Galletas de nueces y almendras", "Prueba estas deliciosas galletas de nueces y almendra en la próxima fiesta o evento especial que tengas y verás que le encantarán a a todos tus invitados porque están riquísimas. En vez de dar típicas galletas caseras de toda la vida, añade un toque de sabor con las nueces picadas y verás como cambia la cosa a mejor si es que este fruto seco te gusta.", 4000, 100, "galletas", "https://cambiatuvida.cl/wp-content/uploads/2018/07/galletas-avena-almendras-nueces-ctv-830-x-420.jpg"),
("Galletas de centeno", "Estamos seguros de que estas galletas de centeno de nuestro establecimiento les van a encantar. Hechas con harina integral de centeno y aceite de oliva, en lugar de mantequilla. Son perfectas para el desayuno o la merienda. ¡La mejor opción para llevar a casa!", 1000, 1000, "galletas", "https://www.hogarmania.com/archivos/201902/galletas-de-centeno-xl-XxXx80.jpg"),
("Surtido de galletas", "El surtido de galletas es perfecto para servir galletas variadas y para todos los gustos. Es la oportunidad perfecta para llevarte un poco de las mejores 5 galletas de nuestro establecimiento ¡ y lo mejor ! puedes personalizarla a tu gusto y enviársela a esa persona especial.", 25000, 100, "galletas", "https://www.hogarmania.com/archivos/201707/cabi0052-joseba-surtido-de-galletas-xl-1280x720x80xX.jpg");